-- Lab2: Read Uncommitted- Tx 2 on mysql
-- Jeongkyu Lee
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- Tx 1: SELECT * FROM ACCT;
-- Tx 1: UPDATE ACCT SET BAL = 200 WHERE ID = 'A';
-- TX 1: SELECT * FROM ACCT;
SELECT * FROM ACCT;
-- Tx 1: COMMIT;;
-- Tx 1: SELECT * FROM ACCT;
SELECT * FROM ACCT;
