-- Lab3: Repeatable Read- Tx 2 on mysql
-- Jeongkyu Lee
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT ID FROM ACCT WHERE BAL = 200;
-- Tx 1: SELECT * FROM ACCT;
-- Tx 1: INSERT INTO ACCT VALUES ('C', 200);
-- TX 1: SELECT * FROM ACCT;
SELECT ID FROM ACCT WHERE BAL = 200;
-- Tx 1: COMMIT;;
-- Tx 1: SELECT * FROM ACCT;
SELECT ID FROM ACCT WHERE BAL = 200;
