-- Lab3: Repeatable Read- Tx 1 on mysql
-- Jeongkyu Lee
SET AUTOCOMMIT = 0
SELECT * FROM ACCT;
INSERT INTO ACCT VALUES ('C', 200);
SELECT * FROM ACCT;
-- Tx 2: SELECT ID FROM ACCT WHERE BAL = 200;
COMMIT;;
SELECT * FROM ACCT;
-- Tx 2: SELECT ID FROM ACCT WHERE BAL = 200;
