runtime: java17
instance_class: F2

entrypoint: java -jar target/demo-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://35.238.165.15:5432/mydb"
  SPRING_DATASOURCE_USERNAME: "myuser"
  SPRING_DATASOURCE_PASSWORD: "yourpassword"
